# developer - sets up all the stuff needed for developing software
# requires 'developers' dict
# developers:
#   <username>:
#     email: <email address>

- assert:
    that: developers is defined
    msg: "'developers' dict needs to be defined"

- name: install dependencies for development
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - vim
    # Java
    - jre-openjdk
    - jdk-openjdk
    - openjdk-doc
    - openjdk-src
    - java-openjfx 
    - java-openjfx-doc
    - java-openjfx-src
    - gradle
    - jdk11-openjdk
    - openjdk11-doc
    - openjdk11-src
    - jdk8-openjdk
    - openjdk8-doc
    - openjdk8-src
    - maven
    # docker
    - docker
    - docker-compose
    # javascript
    - nodejs
    - npm
    # C & C++
    - make
    - cmake
    - gcc
    # Vulkan
    - vulkan-headers
    - vulkan-tools
    - vulkan-validation-layers
    - vulkan-extra-layers
    - vulkan-trace

- name: install aur dependencies for development
  become_user: aur_builder
  aur:
    name:
      # testing
      - postman-bin
      - soapui
      # IDE
      - jetbrains-toolbox

#
# groups
#
- name: create group groups
  group:
    name: "{{ item }}"
    state: present
  loop:
    # for common stuff like idea dir ownership
    - developers
    # to run docker without sudo
    - docker
- name: add users to groups
  user:
    name: "{{ item.key }}"
    groups: developers, docker
    append: yes
  loop: "{{ q('dict', developers) }}"


#
# start docker service
#
- name: start docker service
  systemd:
    name: docker
    state: started
    enabled: yes


#
# remove old Intellij installation
#
- name: remove old Idea dir
  file:
    state: absent
    path: /opt/idea
- name: remove old Idea start script
  file:
    state: absent
    path: ~{{ item.key }}/.local/bin/idea.sh
  loop: "{{ q('dict', developers) }}"


#
# setup git
#
- name: setup git
  copy:
    dest: ~{{ item.key }}/.gitconfig
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: u=rw,g=rw,o=r
    content: |
      [user]
      email = "{{ item.value.email }}"
      name = "{{ item.value.fullname }}"
      [core]
      editor=vim
      [pull]
      ff=only
  loop: "{{ q('dict', developers) }}"


#
# install rust
#
- name: download Rust install script
  get_url:
    url: https://static.rust-lang.org/rustup.sh
    dest: /tmp/rustup.sh
    mode: +x
- name: run Rust install script
  # each user needs to run this script
  become_user: "{{ item.key }}"
  shell: /tmp/rustup.sh -y
  loop: "{{ q('dict', developers) }}"
- name: add cargo dir to users PATH
  lineinfile:
    path: ~{{ item.key }}/.profile
    line: '"PATH=$HOME/.cargo/bin:$PATH"'
  loop: "{{ q('dict', developers) }}"
