---
- hosts: choinka
  become_user: root
  become: yes
  gather_facts: False
  roles:
    - accounts_setup
    - essential_admin_tools      
    - in_poland
    - with_hostname 
    - with_sound
    - with_SSD 
    - with_GUI
    - java_developer
    - dropbox
    - logitech_wireless
    - office

  vars:
    with_GUI__is_4k: True
    dropbox_users:
      - marek

  tasks:
  - name: enable dhcpcd
    systemd:
      name: dhcpcd
      state: started
      enabled: yes


  - name: install some usefull software
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - keepassxc


  #
  # spotify
  #
  - name: check if spotify is installed
    command: pacman -Qi spotify
    register: spotify_is_installed
    ignore_errors: True
    changed_when: False
  - name: install spotify
    block:
      - name: download spotify signature
        get_url:
          url: https://download.spotify.com/debian/pubkey.gpg
          dest: /tmp/spotify-public-key.asc
      - name: import spotify signature
        command: gpg --import /tmp/spotify-public-key.asc
      - name: install spotify
        become_user: aur_builder
        aur:
          name: spotify
          skip_installed: yes
    when: spotify_is_installed.rc != 0
