---
- hosts: choinka
  connection: local
  become_user: root
  become: yes
  gather_facts: False
  roles:
    - accounts_setup
    - essential_admin_tools
    - with_network_cable
    - with_GUI
    - in_poland
    - with_hostname
    - with_sound
    - with_SSD
    - developer
    - dropbox
    - logitech_wireless
    - office
    - common_software
    - gaming

  vars:
    with_GUI__is_4k: True
    users_to_setup:
      - root
      - marek
    dropbox_users:
      - marek
    developers: "{{ vault_developers }}"
    wegiel_ip: "{{ vault_wegiel_ip }}"

  tasks:
    #
    # install CPU microcode upgreade
    #
    - name: install AMD CPU microcode upgreades
      pacman:
        name: amd-ucode
        state: present
    #
    # prepare backup to wegiel
    #
    - name: install rsync
      pacman:
        name: rsync
        state: present
    - name: create backup script
      template:
        src: choinka_backup_to_wegiel.sh
        dest: ~marek/.local/bin/backup_to_wegiel
        mode: 'u=rwx,go=r'
        owner: marek
        group: marek
    #
    # guitar stuff
    #
    - name: install guitar software
      pacman:
        name: "{{ item }}"
        state: present
      loop:
        - jack2
        - jack2-dbus
        - qjackctl
        - guitarix
        - realtime-privileges
        - pulseaudio-jack
        - ardour
    - name: add user to realtime group
      user:
        name: marek
        groups: realtime
        append: yes
    - name: run qjackctl with i3
      blockinfile:
        path: /home/marek/.config/i3/config
        block: |
          exec qjackctl
        marker: "# {mark} ANSIBLE MANAGED BLOCK enable run qjackctl"

    # LLM
    - name: install software for LLM stuff
      pacman:
        name: "{{ item }}"
        state: present
      loop:
        # monitor GPU usage
        - nvtop
        # ROCm rocm-hip-sdk rocm-smi-lib
        - rocm-hip-sdk
        - rocm-smi-lib
        # AMD's library for high-performance machine learning primitives.
        - miopen-hip
    - name: install software for LLM stuf from AUR
      become_user: aur_builder
      aur:
        name: "{{ item }}"
        state: present
      loop:
        - koboldcpp-bin
        # llm chat using AMD GPU
        # - koboldcpp-hipblas - takes too long to install with ansible, install separately

    # cleanup
    - name: include cleanup tasks
      include_tasks: clean_up.yaml