---
- hosts: choinka
  become_user: root
  become: yes
  gather_facts: False
  roles:
    - accounts_setup
    - essential_admin_tools
    - with_network_cable
    - in_poland
    - with_hostname 
    - with_sound
    - with_SSD 
    - with_GUI
    - developer
    - dropbox
    - logitech_wireless
    - office
    - common_software

  vars:
    with_GUI__is_4k: True
    users_to_setup:
      - root
      - marek
    dropbox_users:
      - marek
    developers:
      marek:
        email: tirpitz-verus@gmail.com
        fullname: Marek Lesiewski

  tasks:

    - name: install AMD CPU microcode upgreades
      pacman:
        name: amd-ucode
        state: present
