---
- hosts: choinka
  connection: local
  become_user: root
  become: yes
  gather_facts: False
  roles:
#    - accounts_setup
#    - essential_admin_tools
#    - with_network_cable
#    - with_GUI
#    - in_poland
#    - with_hostname
#    - with_sound
#    - with_SSD
#    - developer
#    - dropbox
#    - logitech_wireless
#    - office
#    - common_software
#    - gaming
#    - yubikey
#    - with_bluetooth
#    - using_printer

  vars:
    with_GUI__is_4k: True
    users_to_setup:
      - root
      - marek
    dropbox_users:
      - marek
    developers: "{{ vault_developers }}"
    wegiel_ip: "{{ vault_wegiel_ip }}"

  tasks:
    #
    # install CPU microcode upgreade
    #
    - name: install AMD CPU microcode upgreades
      pacman:
        name: amd-ucode
        state: present
    #
    # prepare backup to wegiel
    #
    - name: install rsync
      pacman:
        name: rsync
        state: present
    - name: create backup script
      template:
        src: choinka_backup_to_wegiel.sh
        dest: ~marek/.local/bin/backup_to_wegiel
        mode: 'u=rwx,go=r'
        owner: marek
        group: marek

    # cleanup
    - name: include cleanup tasks
      include_tasks: clean_up.yaml
