# list of general cleanup tasks

# 2022-02-09 cleanup after an update adding :ALL in visudo
- name: 2022-02-09 remove old entry
  lineinfile:
    dest: /etc/sudoers
    state: absent
    line: '%systemupdater ALL=(ALL) NOPASSWD: /usr/bin/pacmatic'
    validate: 'visudo -cf %s'
- name: 2022-02-09 remove old entry
  lineinfile:
    dest: /etc/sudoers
    state: absent
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
- name: 2022-02-09 remove old entry
  lineinfile:
    path: /etc/sudoers
    state: absent
    line: '%wifi ALL=(ALL) NOPASSWD: /bin/wifi-menu'
    validate: 'visudo -cf %s'
- name: 2022-02-09 remove old entry
  lineinfile:
    path: /etc/sudoers
    state: absent
    line: '%wifi ALL=(ALL) NOPASSWD: /bin/netctl'
    validate: 'visudo -cf %s'

- name: 2022-06-09 remove klavaro
  pacman:
    name: klavaro
    state: absent

- name: 2022-08-19 remove rednotebook
  pacman:
    name: "{{ item }}"
    state: absent
  loop:
    - rednotebook

- name: 2022-08-20 remove old versions of java
  pacman:
    name: "{{ item }}"
    state: absent
  loop:
    - openjdk11-src
    - openjdk11-doc
    - jdk11-openjdk
    - openjdk8-src
    - openjdk8-doc
    - jdk8-openjdk

- name: 2023-02-06 remove unneeded testing tools
  pacman:
    name: "{{ item }}"
    state: absent
  loop:
    - soapui
    - postman-bin

- name: 2023-02-25 use spotify-launcher instead of repackaged AUR version of spotify (package)
  pacman:
    name: spotify
    state: absent
- name: 2023-02-25 use spotify-launcher instead of repackaged AUR version of spotify (script)
  ansible.builtin.file:
    path: /home/marek/.local/bin/spotify-hdpi.sh
    state: absent

- name: 2023-04-12 remove related Postman directories (not needed after 2023-02-06 Postman removal)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /home/marek/Postman
    - /home/marek/.config/Postman
- name: 2023-06-25 stop using pacmatic (use yay instead)
  pacman:
    name: pacmatic
    state: absent