---
- hosts: computor
  become_user: root
  become: yes
  gather_facts: False
  roles:
    - accounts_setup
    - essential_admin_tools
    - with_network_cable
    - in_poland
    - with_hostname  
    - with_bluetooth
    - with_battery
    - with_sound
    - with_SSD  
    - with_wifi
    - with_swapfile 
    - with_GUI
    - developer
    - dropbox
    - common_software
    
  vars:
    with_GUI__is_4k: False
    users_to_setup:
      - root
      - marek
    dropbox_users:
      - marek
    developers:
      marek:
        email: marek.lesiewski@ipfdigital.com
        fullname: Marek Lesiewski

  tasks:
    #
    # pritunl
    #
    - name: check if pritunl client installed
      shell: 'grep pritunl /etc/pacman.conf'
      register: pritunl_present
      changed_when: False
      ignore_errors: True
    - debug:
        var: pritunl_present
    - name: enable pritunl repository
      block:
        - name: add pritunl repository
          become: yes
          blockinfile:
            path: /etc/pacman.conf
            block: |
              # enable pritunl
              [pritunl]
              Server = https://repo.pritunl.com/stable/pacman
        - name: download pritunl key
          command: pacman-key --keyserver hkp://keyserver.ubuntu.com -r 7568D9BB55FF9E5287D586017AE645C0CF8E292A
        - name: sign pritunl key
          command: pacman-key --lsign-key 7568D9BB55FF9E5287D586017AE645C0CF8E292A
        - name: download pacman repos
          command: pacman -Sy
      when: pritunl_present.rc != 0
    - name: install pritunl client apps
      pacman:
        name: "{{ item }}"
        state: present
      loop:
        - pritunl-client-electron
        - pritunl-client-electron-numix-theme