---
- hosts: kontomarek
  connection: local
  become_user: root
  become: yes
  gather_facts: False
  roles:
    - accounts_setup
    - essential_admin_tools
    - with_GUI
    - in_poland
    - with_hostname
    - with_bluetooth
    - with_battery
    - with_sound
    - with_SSD
    - with_wifi
    - developer
    - dropbox
    - common_software
    - office

  vars:
    with_GUI__is_4k: False
    with_GUI__dualscreen:
      right: HDMI1
      left: eDP1
    users_to_setup:
      - root
      - marek
    dropbox_users:
      - marek
    developers: "{{ vault_developers }}"

  tasks:
    #
    # additional software
    #
    - name: install software needed by kontomatik
      pacman:
        name: "{{ item }}"
        state: present
      loop:
        # for yubikey
        - yubikey-manager
        - yubikey-manager-qt
        - yubikey-personalization
        - yubikey-personalization-gui
        # mail client
        - thunderbird
        # network stuff - 192.168.151.1 DNS
        - openvpn
        - systemd-resolvconf
        # session locking
        - xautolock
        # save power with Intel CPU
        - powertop
        # web browser that can use blur in google meet
        - chromium
        # rsync is needed for deployments
        - rsync

    #
    # allow lid closed
    #
    - name: prevent hibernation on lid close
      blockinfile:
        path: /etc/systemd/logind.conf
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        block: |
          HandleLidSwitch=ignore
          HandleLidSwitchExternalPower=ignore
          HandleLidSwitchDocked=ignore
          IdleAction=ignore

    #
    # bluetooth peripherals on AC
    #
    - name: switch on bluetooth by default in TLP
      blockinfile:
        create: yes
        path: /etc/tlp.d/01-bluetooth-on-ac.conf
        block:
          DEVICES_TO_ENABLE_ON_AC="bluetooth"
    - name: set bluetooth policy to auto-enabled
      lineinfile:
        regexp: "^#AutoEnable=false$"
        state: present
        path: /etc/bluetooth/main.conf
        line: AutoEnable=true
    - name: set bluetooth policy to fast-connectable
      lineinfile:
        regexp: "^#FastConnectable=false$"
        state: present
        path: /etc/bluetooth/main.conf
        line: FastConnectable=true
    - name: enable bluetoothd
      systemd:
        name: bluetooth.service
        state: started
        enabled: yes

    #
    # some additional i3 settings
    #
    - name: autolock in i3
      lineinfile:
        path: /home/marek/.config/i3/config
        state: present
        insertafter: EOF
        line: exec_always --no-startup-id xautolock -time 5 -locker "i3lock -fi /home/marek/.config/i3/lock.png"
        regexp: 'xautolock'
        validate: i3 -c %s -C

    #
    # VPN
    #
    - name: create stub-resolv symbolic link
      ansible.builtin.file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        state: link
        force: yes
    - name: install openvpn-update-systemd-resolved
      become_user: aur_builder
      aur:
        name:
          - openvpn-update-systemd-resolved

    #  
    # cleanup
    #
    - name: include cleanup tasks
      include_tasks: clean_up.yaml
