---
- name: post install tasks
  hosts: localhost
  tasks:



  - name: install mikrocode upgreade
    pacman:
      name: intel-ucode
      state: present    
  
  # configure grub
  - name: check if grub set up
    shell: ls /boot/grub
    register: boot_grub_files
  - name: add cryptdevice to grub
    lineinfile:
      state: present
      dest: "/etc/default/grub"
      backrefs: yes
      regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=(?!.*cryptdevice)\"[^\"]+)(\".*)'
      line: '\1 cryptdevice=/dev/nvme0n1p3:volgroup1\2'
    when: boot_grub_files.stdout.find('grub.cfg') == -1
  - name: create boot EFI directory
    file:
      path: "/boot/EFI"
      state: directory
  - name: mount UEFI partition
    mount:
      path: "/boot/EFI"
      src: "/dev/nvme0n1p1"
      state: mounted
      fstype: vfat
  - name: run grub-install
    command: grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck
    when: boot_grub_files.stdout.find('grub.cfg') == -1
  - name: copy grub messages
    copy:
      dest: "/boot/grub/locale/en.mo"
      src: "/usr/share/locale/en@quot/LC_MESSAGES/grub.mo"
  - name: run grub-mkconfig
    command: grub-mkconfig -o /boot/grub/grub.cfg
    when: boot_grub_files.stdout.find('grub.cfg') == -1
      

  - name: create vimrc with powerline settings
    lineinfile:
      dest: /etc/vimrc
      line: let g:powerline_pycmd="py3"


