---
- hosts: xps13
  become_user: root
  become: yes
  gather_facts: False
  roles:
    - accounts_setup
    - essential_admin_tools      
    - in_poland
    - with_hostname  
    - with_bluetooth
    - with_battery  
    - with_sound
    - with_SSD  
    - with_wifi
    - with_swapfile 
    - with_GUI
    - office
    - developer
    - dropbox
    - common_software

  vars_prompt:
    - name: "my_password"
      prompt: "Enter password"
      private: yes

  vars:
    with_GUI__is_4k: True
    users_to_setup:
      - root
      - marek
    dropbox_users:
      - marek
    developers:
      marek:
        email: tirpitz-verus@gmail.com
        fullname: Marek Lesiewski

  tasks:

  - name: install intell CPU mikrocode upgreade
    pacman:
      name: intel-ucode
      state: present

  - name: install steam
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - lib32-gtk2
      - lib32-libva1
      - lib32-libva
      - lib32-libvdpau
      - steam
