---
- hosts: xps13
  become_user: root
  become: yes
  gather_facts: False
  roles:
    - accounts_setup
    - essential_admin_tools      
    - in_poland
    - with_hostname  
    - with_bluetooth
    - with_battery  
    - with_sound
    - with_SSD  
    - with_wifi
    - with_swapfile 
    - with_GUI
    - office


  vars_prompt:
    - name: "my_password"
      prompt: "Enter password"
      private: yes

  vars:
    with_GUI__is_4k: False
    ansible_connection: local
    users_to_setup:
      - root
      - marek
    dropbox_users:
      - marek
  
  tasks:

  - name: install docker
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - docker
      - docker-compose

  - name: name install spotify (music player)
    become: yes
    become_user: marek
    aur:
      name: spotify
      skip_installed: false
  - name: create script for running spotify
    copy:
      dest: /home/marek/bin/spotify-hdpi
      content: spotify --force-device-scale-factor=2.0 %U
      mode: 0744

  - name: install keepassxc
    become: yes
    pacman:
      name: keepassxc
      state: present



  - name: set Logitech MX Ergo acceleration
    lineinfile:
      path: /home/marek/.config/i3/config
      line: exec_always xinput --set-prop 10 'libinput Accel Speed' 1
  - name: install solaar
    become: yes
    pacman:
      name: solaar
      state: present
  - name: create group plugdev (to run solaar)
    become: yes
    group:
      name: plugdev
      state: present
  - name: add user to plugdev group
    user:
      name: marek
      groups: plugdev
      append: yes
  
  - name: install prerequisits for persnal journal
    become: yes
    pacman:
      name: binutils
      state: present
  - name: install personal journal
    become: yes
    become_user: marek
    aur:
      name: rednotebook
      skip_installed: false

  - name: install typing trainer
    become: yes
    pacman:
      name: klavaro
      state: present

  - name: install steam
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - lib32-gtk2
      - lib32-libva1
      - lib32-libva
      - lib32-libvdpau
      - steam
  

  - name: install comunicators
    become: yes
    become_user: marek
    aur:
      name: "{{ item }}"
      skip_installed: false
    loop:
      - slack-desktop
      - skypeforlinux-stable-bin
  - name: install communicators
    become: yes
    pacman:
      name: weechat
      state: present

  - name: install graphical software
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - gimp
      - sane
      - skanlite
      - krita
      - blender
      - deepin-screenshot

  - name: install calibre
    become: yes
    pacman:
      name: calibre
      state: present


  - name: install JavaScript dev things
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - nodejs
      - npm

  - name: install system programming tools
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - make
      - cmake
      - gcc
      - vulkan-headers
      - vulkan-tools
      - vulkan-validation-layers
      - vulkan-extra-layers
      - vulkan-trace
   
  - name: setup git
    copy:
      dest: /home/marek/.gitconfig
      owner: marek
      group: marek
      mode: u=rw,g=rw,o=r
      content: |
        [user]
        email = tirpitz-verus@gmail.com
        name = Marek Lesiewski
        [core]
        editor=vim

  - name: install tuxguitar
    become: yes
    become_user: marek
    aur:
      name: tuxguitar
