---
- hosts: xps13
  connection: local
  become_user: root
  become: yes
  gather_facts: False
  roles:
    - accounts_setup
    - essential_admin_tools      
    - with_GUI
    - in_poland
    - with_hostname
    - with_bluetooth
    - with_battery
    - with_sound
    - with_SSD
    - with_wifi
    - office
#    - developer
#    - dropbox
    - common_software
#    - gaming

  vars:
    with_GUI__is_4k: True
    users_to_setup:
      - root
      - marek
      - dorota

  tasks:

  - name: install intell CPU mikrocode upgreade
    pacman:
      name: intel-ucode
      state: present

  # cleanup
  - name: include cleanup tasks
    include_tasks: clean_up.yaml
