---
- hosts: xps13
  become_user: root
  become: yes
  gather_facts: False
  roles:
    - accounts_setup
    - essential_admin_tools      
    - in_poland
    - with_hostname  
    - with_bluetooth
    - with_battery  
    - with_sound
    - with_SSD  
    - with_wifi
    - with_swapfile 
    - with_GUI


  vars_prompt:
    - name: "my_password"
      prompt: "Enter password"
      private: yes

  tasks:

  - name: check shell
    command: "echo $SHELL"
    register: my_shell
  - name: install oh-my-zsh
    expect:
      command: "curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
      responses:
        (?!)password: "{{ my_password }}"
    when: my_shell.stdout.find('/bin/zsh') == -1

        
  - name: create directory for systemd user units
    file:
      path: /home/marek/.config/systemd/user
      state: directory
      owner: marek
      group: marek
  - name:
    copy:
      dest: /home/marek/.config/systemd/user/marek.targer
      content: |
        [Unit]
        Description=Marek's target
        
        [Install]
        Alias=default.target
      owner: marek
      group: marek

  - name: install docker
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - docker
      - docker-compose

  - name: name install spotify (music player)
    become: yes
    become_user: marek
    aur:
      name: spotify
      skip_installed: false
  - name: create script for running spotify
    copy:
      dest: /home/marek/bin/spotify-hdpi
      content: spotify --force-device-scale-factor=2.0 %U
      mode: 0744

  - name: install dropbox 
    become: yes
    become_user: marek
    aur:
      name: dropbox
      skip_installed: false
  - name: create dropbox systemd unit
    copy:
      dest: /home/marek/.local/share/systemd/user/dropbox-marek.service
      content: |
        [Unit]
        Description=Dropbox service for marek
        
        [Service]
        Type=simple
        ExecStart=/home/marek/.dropbox-dist/dropboxd
        Restart=on-failure
        RestartSec=1
        Environment=DISPLAY=:0

        [Install]
        WantedBy=multi-user.target
      owner: marek
      group: marek
  - name: Register uid of user marek
    command: id -u marek
    register: user_uid
  - name: reload systemd
    become: yes
    become_user: marek
    command: systemctl --user daemon-reload
    environment:
      XDG_RUNTIME_DIR: /run/user/{{user_uid.stdout}}
  - name: enable dropbox service
    become: yes
    become_user: marek
    command: systemctl --user enable /home/marek/.local/share/systemd/user/dropbox-marek.service
    environment:
      XDG_RUNTIME_DIR: /run/user/{{user_uid.stdout}}

  - name: install keepassxc
    become: yes
    pacman:
      name: keepassxc
      state: present



  - name: set Logitech MX Ergo acceleration
    lineinfile:
      path: /home/marek/.config/i3/config
      line: exec_always xinput --set-prop 10 'libinput Accel Speed' 1
  - name: install solaar
    become: yes
    pacman:
      name: solaar
      state: present
  - name: create group plugdev (to run solaar)
    become: yes
    group:
      name: plugdev
      state: present
  - name: add user to plugdev group
    user:
      name: marek
      groups: plugdev
      append: yes


  - name: check if idea is installed
    stat:
      path: /opt/idea
    register: idea_dir
  - name: install openjdk
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - jre-openjdk
      - jdk-openjdk
      - openjdk-doc
      - java-openjfx 
      - java-openjfx-doc
      - gradle
      - jdk8-openjdk
  - name: download intellij idea
    get_url:
      url: https://download.jetbrains.com/idea/ideaIU-2018.3.tar.gz
      dest: /var/tmp/ideaIU.tar.gz
    when: idea_dir.stat.exists == False
  - name: create group idea
    become: yes
    group:
      name: idea
      state: present
  - name: add marek to idea
    become: yes
    user:
      name: marek
      groups: idea
      append: yes
  - name: create idea dir
    become: yes
    file:
      path: /opt/idea
      group: idea
      owner: root
      mode: g=rwx
      state: directory
  - name: unpack intellij
    become: yes
    when: idea_dir.stat.exists == False
    unarchive:
      src: /var/tmp/ideaIU.tar.gz
      dest: /opt/idea
      group: idea
      owner: root
      mode: g=rwx


  - name: install prerequisits for persnal journal
    become: yes
    pacman:
      name: binutils
      state: present
  - name: install personal journal
    become: yes
    become_user: marek
    aur:
      name: rednotebook
      skip_installed: false

  - name: install document viwer
    become: yes
    pacman:
      name: xreader
      state: present

  - name: install typing trainer
    become: yes
    pacman:
      name: klavaro
      state: present

  - name: install libre office
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - libreoffice-still
      - libreoffice-still-pl
      - hunspell
      - hunspell-pl
      - hyphen 
      - hyphen-pl
#      - mythes
#      - mythes-pl

  - name: install steam
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - lib32-gtk2
      - lib32-libva1
      - lib32-libva
      - lib32-libvdpau
      - steam
  

  - name: install comunicators
    become: yes
    become_user: marek
    aur:
      name: "{{ item }}"
      skip_installed: false
    loop:
      - slack-desktop
      - skypeforlinux-stable-bin
  - name: install communicators
    become: yes
    pacman:
      name: weechat
      state: present

  - name: install calculator
    become: yes
    pacman:
      name: calc
      state: present

  - name: install graphical software
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - gimp
      - sane
      - skanlite
      - krita
      - blender
      - deepin-screenshot

  - name: install calibre
    become: yes
    pacman:
      name: calibre
      state: present

  - name: install gaming software
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - libldap
      - lib32-libldap
      - vulkan-intel
      - wine
      - wine_gecko
      - wine-mono
      - lutris
  - name: install dxvk-bin
    become: yes
    become_user: marek
    aur:
      name: dxvk-bin
      skip_installed: false

  - name: install JavaScript dev things
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - nodejs
      - npm

  - name: install system programming tools
    become: yes
    pacman:
      name: "{{ item }}"
      state: present
    loop:
      - make
      - cmake
      - gcc
      - vulkan-headers
      - vulkan-tools
      - vulkan-validation-layers
      - vulkan-extra-layers
      - vulkan-trace
   
  - name: setup git
    copy:
      dest: /home/marek/.gitconfig
      owner: marek
      group: marek
      mode: u=rw,g=rw,o=r
      content: |
        [user]
        email = tirpitz-verus@gmail.com
        name = Marek Lesiewski
        [core]
        editor=vim

  - name: install tuxguitar
    become: yes
    become_user: marek
    aur:
      name: tuxguitar
