#!/usr/bin/env bash

# exit if no wifi
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

# colors
RED="#FF0000"
GREEN="#00FF00"
YELLOW="#EEFF00"
ORANGE="#FFAA00"

# set starting values
SHORT_TEXT=""
FULL_TEXT="$INTERFACE"
COLOR="$RED"

# by op state
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    # if no connection
    SHORT_TEXT="$INTERFACE down"
    FULL_TEXT="$INTERFACE down"
    COLOR="$RED"
else
    # we have connection
    
    # add SSID
    SSID=$(iw "$INTERFACE" info | awk '/ssid/ {print $2}')
    SHORT_TEXT="$SHORT_TEXT $SSID"
    FULL_TEXT="$FULL_TEXT $SSID"

    # quality
    QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    SHORT_TEXT="$SHORT_TEXT $QUALITY%"
    FULL_TEXT="$FULL_TEXT $QUALITY%"
    if [[ $QUALITY -ge 80 ]]; then
        COLOR="$GREEN"
    elif [[ $QUALITY -ge 60 ]]; then
        COLOR="$YELLOW"
    elif [[ $QUALITY -ge 40 ]]; then
        COLOR="$ORANGE"
    fi
fi


# print output
echo $SHORT_TEXT
echo $FULL_TEXT
echo $COLOR
