# with_swapfile - 
  
  - name: search for existing swapfile
    shell: ls /
    register: root_files_list
    changed_when: False
  - name: allocate swapfile
    command: dd if=/dev/zero of=/swapfile bs=1G count=16 status=progress
    when: root_files_list.stdout.find('swapfile') == -1
  - name: set swapfile permissions
    file:
      path: "/swapfile"
      owner: root
      group: root
      mode: 0600
  - name: make swap file
    command: mkswap /swapfile
    when: root_files_list.stdout.find('swapfile') == -1
  - name: mount swapfile
    mount:
      src: /swapfile
      path: none
      fstype: swap
      state: present
    when: root_files_list.stdout.find('swapfile') == -1

