# with_sound - installs sound software

- name: install pipewire
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - pipewire
    - pipewire-pulse
    - pipewire-audio
    - pipewire-alsa
    - wireplumber # session manager for pipewire

- name: install pipewire software from AUR
  become_user: aur_builder
  aur:
    name: pwvucontrol # gui for pipewire


