# with_GUI - install graphics drivers and windows

#
# install drivers
#
- name: check VGA
  shell: lspci | grep VGA
  register: vga_output
  changed_when: False
- name: install mesa
  pacman:
    name: "{{ item }}"
    state: present
  loop:    
    - mesa
    - libva-mesa-driver
- name: install Radeon drivers
  pacman:
    name: "{{ item }}"
    state: present
  loop:    
    - xf86-video-amdgpu
    - vulkan-radeon
  when: "'Radeon' in vga_output.stdout"
- name: install Intell drivers
  pacman:
    name: "{{ item }}"
    state: present
  loop:    
    - xf86-video-intel
    - vulkan-intel
  when: "'Intel' in vga_output.stdout"

#
# install GUI 
#
- name: install wayland and related software
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - hyprland
    - waybar
    - kitty # terminal
    - dolphin # file manager
    - wofi # app launcher
    - hyprpaper # wallpapers backend
    - waypaper # wallpapers chooser
    - nwg-look # GTK themes
    - wl-clipboard # clipboard manager between wayland and unix pipes
    - hyprlock # session lock
    - cliphist # clipboard history manager
    - xdg-desktop-portal-hyprland # for screensharing

- name: install wayland related software from AUR
  become_user: aur_builder
  aur:
    name: "{{ item }}"
  loop:
    - vimv # image viewer

#
# add users to input group
#
- name: add users to input group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: input
    append: yes
  loop: "{{ users_to_setup }}"

#
# setup hyprland
#
- name: copy kitty config
  copy:
    src: kitty
    dest: "~{{ item }}/.config/"
    owner: "{{ item }}"
    group: "{{ item }}"
    directory_mode: u
  loop: "{{ users_to_setup }}"
- name: copy waybar config
  copy:
    src: waybar
    dest: "~{{ item }}/.config/"
    owner: "{{ item }}"
    group: "{{ item }}"
    directory_mode: u
  loop: "{{ users_to_setup }}"
- name: copy hyprland & hyprpaper config
  copy:
    src: hypr
    dest: "~{{ item }}/.config/"
    owner: "{{ item }}"
    group: "{{ item }}"
    directory_mode: u
  loop: "{{ users_to_setup }}"
- name: copy waypaper config
  copy:
    src: waypaper
    dest: "~{{ item }}/.config/"
    owner: "{{ item }}"
    group: "{{ item }}"
    directory_mode: u
  loop: "{{ users_to_setup }}"

#
# install GUI
#
- name: fonts
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - ttf-dejavu
    - otf-font-awesome
