# with_bluetooth - installs bluez

- name: install bluetooth software
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - bluez
    - bluez-utils

- name: start bluetooth service
  systemd:
    name: bluetooth.service
    state: started
    enabled: yes