# accounts_setup - sets up user accounts
 
- name: create accounts
  user:
    name: "{{ item }}"
    create_home: yes
  loop: "{{ users_to_setup }}"
  when: item != 'root'
- name: create systemd dir
  become_user: "{{ item }}"
  ansible.builtin.file:
    path: ~/.config/systemd/user
    state: directory
  loop: "{{ users_to_setup }}"
  when: item != 'root'
