# with_network_cable - enable automatic cable network
- name: install network software
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    # DHCP client
    - dhcpcd
- name: enable dhcp client
  systemd:
    name: dhcpcd
    state: started
    enabled: yes
