  - name: set hostname
    copy:
      dest: "/etc/hostname"
      content: "{{ inventory_hostname }}"

  - name: set hosts contents
    copy:
      dest: "/etc/hosts"
      content: |
        127.0.0.1	localhost.localdomain		localhost
        ::1		localhost.localdomain		localhost
        127.0.1.1	{{ inventory_hostname }}.localdomain	{{ inventory_hostname }}
 
