# common_software - installs commonly used software

#
# install from official repo
#
- name: install common software
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    # manage passwords
    - keepassxc
    # graphics software
    - gimp
    - blender
    - krita
    # scan documents
    - sane
    - skanlite
    # manage e-books
    - calibre
    # firewall
    - firewalld
    # communicator
    - signal-desktop
    # screen capture
    - maim
    # spotify launcher not to deal with changing PGP keys
    - spotify-launcher
    # 7zip archives
    - p7zip


#
# spotify-launcher post install
#
- name: configure spotify-launcher
  become_user: '{{ item }}'
  copy:
    dest: ~{{ item }}/.config/spotify-launcher.conf
    src: spotify-launcher.conf
  loop: "{{ users_to_setup }}"
  when: "with_GUI__is_4k"

#
# install from AUR
#
- name: install common software from AUR
  become_user: aur_builder
  aur:
    name:
      # communicators
      - slack-desktop
      - skypeforlinux-stable-bin
      - zoom
      # QMK keyboard setup
      - vial-appimage


#
# start firewall
#
- name: start firewalld
  systemd:
    name: firewalld.service
    state: started
    enabled: yes
