# common_software - installs commonly used software

#
# install from official repo
#
- name: install common software
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    # manage passwords
    - keepassxc
    # graphics software
    - gimp
    - blender
    - krita
    # scan documents
    - sane
    - skanlite
    # manage e-books
    - calibre
    # firewall
    - firewalld
    # communicator
    - signal-desktop
    # screen capture
    - maim
    # spotify launcher not to deal with changing PGP keys
    - spotify-launcher
    # 7zip archives
    - p7zip
    # *.torrent client
    - qbittorrent
    # knowledge base software
    - obsidian
    # notifications software
    - dunst


#
# spotify-launcher post install
#
- name: configure spotify-launcher
  become_user: '{{ item }}'
  copy:
    dest: ~{{ item }}/.config/spotify-launcher.conf
    src: spotify-launcher.conf
  loop: "{{ users_to_setup }}"
  when: "with_GUI__is_4k"

#
# install from AUR
#
- name: install common software from AUR
  become_user: aur_builder
  aur:
    name:
      # communicators
      - slack-desktop
      - zoom

#
# start firewall
#
- name: start firewalld
  systemd:
    name: firewalld.service
    state: started
    enabled: yes

#
# copy dusnt config
#
- name: make sure dunst config dir exists
  become_user: '{{ item }}'
  file:
    path: ~{{ item }}/.config/dunst
    state: directory
    recurse: yes
  loop: "{{ users_to_setup }}"
- name : copy dunst config
  become_user: '{{ item }}'
  copy:
    dest: ~{{ item }}/.config/dunst/dunstrc
    src: /etc/dunst/dunstrc
  loop: "{{ users_to_setup }}"