# common_software - installs commonly used software

#
# install from official repo
#
- name: install common software
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    # manage passwords
    - keepassxc
    # graphics software
    - gimp
    - blender
    - krita
    # scan documents
    - sane
    - skanlite
    # manage e-books
    - calibre
    # firewall
    - firewalld
    # communicator
    - signal-desktop
    # screen capture
    - maim
    # spotify launcher not to deal with changing PGP keys
    - spotify-launcher


#
# spotify-launcher post install
#
- name: configure spotify-launcher
  become_user: '{{ item }}'
  copy:
    dest: ~{{ item }}/.config/spotify-launcher.conf
    src: spotify-launcher.conf
  loop: "{{ users_to_setup }}"
  when: "with_GUI__is_4k"

#
# install from AUR
#
- name: install common software from AUR
  become_user: aur_builder
  aur:
    name:
      # communicators
      - slack-desktop
      - skypeforlinux-stable-bin
      - zoom
      # QMK keyboard setup
      - vial-appimage


#
# start firewall
#
- name: start firewalld
  systemd:
    name: firewalld.service
    state: started
    enabled: yes

#
# setup brother DCP-L2532DW printer
#
- name: setup DCP-L2532DW printer
  block:
    - name: install DCP-L2532DW driver
      become_user: aur_builder
      aur:
        name:
          - brother-dcp-l2530dw
    - name: install cups
      pacman:
        name: cups.service
        state: present
    - name: start cups
      systemd:
        name: cups
        state: started
        enabled: yes
    - name: add users to lp group
      user:
        name: "{{ item }}"
        groups: realtime
        append: yes
      loop: "{{ users_to_setup }}"